server:
  port: 8080
spring:
  application:
    name: gateway-backend
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: user-backend
          uri: lb://user-backend
          predicates: Path=/**
        - id: data-backend
          uri: lb://data-backend
          predicates: Path=/**

